config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'boards#index'
  
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'books/search', to: 'books#create'
  delete 'books/reset', to: 'books#destroy'

  get 'books/search', to: 'boards#new'
  
  get 'boards/:board_id/comments', to: 'comments#new'
  
  resources :boards, only: [:index, :show, :new, :create] do
    resources :comments, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates :book_title, uniqueness: { case_sensitive: false }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :boards
  has_many :comments
  accepts_nested_attributes_for :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create]

  def index
    @boards = Board.order(id: :desc).page(params[:page]).per(28)
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = '掲示板を作成しました。'
      redirect_to boards_url
    else
      flash.now[:danger] = '掲示板の作成に失敗しました。'
      render :new
    end
  end

  def new
    @board = current_user.boards.build
  end

  def show
  end
  
  
  private
  
  def board_params
    params.permit(:book_thumbnail_link, :book_title, :book_author)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'net/http'

  def create
    if params[:keyword] != ''
      url = "https://www.googleapis.com/books/v1/volumes?q=#{params[:keyword]}&country=JP"
      @books_data = JSON.parse(Net::HTTP.get(URI.parse(URI.encode(url))))
    else
      flash[:danger] = 'フォームを入力して下さい'
    end
    render new_board_path
  end

  def destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in

  def new
    @board = Board.find(params[:board_id])
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.board_id = params[:board_id]
    if @comment.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_to board_url(params[:board_id])
    else
      if @comment.content.blank?
        flash.now[:danger] = '1文字以上入力して下さい'
      else
        flash.now[:danger] = 'コメントの投稿に失敗しました。'
      end
      @board = Board.find(params[:board_id])
      render :new
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    
    flash[:success] = 'コメントは正常に削除されました'
    redirect_to board_url(params[:board_id])
  end
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/boards/index.html.erb
<div class="row">
  <%= link_to '掲示板作成', new_board_path, class: 'btn btn-dark col-sm-3 mb-3' %>
</div>
<div class="row">
  <% @boards.each do |board| %>
    <div class="col-sm-3 card">
      <%= link_to 'この掲示板を見る',board_path(board.id) , class: 'btn btn-light btn-block my-2' %>
      <img class="text-center card-img-top mt-2" src="<%= board.book_thumbnail_link %>" alt="<%= board.book_title %>">
      <div class="card-body">
        <h4 class="card-title"><%= board.book_title %></h4>
        <h5 class="card-text"><%= board.book_author %></h5>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1>掲示板新規作成</h1>
<h6>※既に作成されている本の掲示板は作成できません。</h6>
<%= render 'books/books_search' %>

<% if @books_data %>
  <div class="row">
    <% if @books_data.dig("items") %>
      <% @books_data["items"].each do |book| %>
        <div class="col-sm-3 card">
          <%= form_with(model: @board, url: '/boards', local: true) do |f| %>
            <%= hidden_field_tag :book_thumbnail_link, book.dig("volumeInfo", "imageLinks", "thumbnail") %>
            <%= hidden_field_tag :book_title, book.dig("volumeInfo", "title") %>
            <%= hidden_field_tag :book_author, book.dig("volumeInfo", "authors", 0) %>
            <%= f.submit '作成', class: 'btn btn-dark btn-block my-2' %>
          <% end %>
          <img class="text-center card-img-top" src="<%= book.dig("volumeInfo", "imageLinks", "thumbnail") %>" alt="<%= book.dig("volumeInfo", "title") %>">
          <div class="card-body">
            <h4 class="card-text"><%= book.dig("volumeInfo", "title") %></h4>
            <h5 class="card-title"><%= book.dig("volumeInfo", "authors", 0) %></h5>
          </div>
        </div>
      <% end %>
    <% else %>
      <h2>本が見つかりませんでした</h2>
    <% end %>
  </div>
<% end %>

app/views/boards/show.html.erb
<% current_board = Board.find(params[:id]) %>
<div class="row">
  <div class="col-sm-3">
    <div class="card mb-3">
      <img class="text-center card-img-top mt-2" src="<%= current_board.book_thumbnail_link %>" alt="<%= current_board.book_title %>">
      <div class="card-body">
        <h4 class="card-title"><%= current_board.book_title %></h4>
        <h5 class="card-text"><%= current_board.book_author %></h5>
        <h6 class="card-text">掲示板作成者：<%= User.find(current_board.user_id).name %></h6>
        <p class="card-text">作成日時：<br><%= current_board.created_at %></p>
      </div>
    </div>
    <%= link_to 'コメント投稿', new_board_comment_path(current_board.id), class: 'btn btn-dark btn-block' %>
  </div>

  <div class="col-sm-8 offset-sm-1">
    <% @comments = current_board.comments.order(id: :desc).page(params[:page]).per(50) %>
    <% comment_count = @comments.count %>
    <% @comments.each do |comment| %>
      <div class="row mb-3">
        <div class="col-sm-11">
          <h4><%= comment_count %> <%= User.find(comment.user_id).name %> <%= comment.created_at %></h4>
          <% comment_count -= 1 %>
          <h5 class="ml-3"><%= raw(h(comment.content).gsub(/\r\n|\r|\n/, "<br>")) %></h5>
        </div>
        <div class="col-sm-1">
          <% if logged_in? && current_user.id == comment.user_id %>
            <%= link_to '削除', board_comment_path(params[:id], comment.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-dark' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/_books_search.html.erb
<%= form_with(url: books_search_path, local: true, class: 'row mb-3') do |f| %>
  <%= f.text_field :keyword, class: 'form-control col-sm-10' %>
  <%= f.submit '本を検索する', class: 'btn btn-dark col-sm-2' %>
<% end %>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h2>コメント投稿フォーム</h2>
    <p>※255文字までしか投稿できません</p>
    <%= form_with(model: [@board, @comment], local: true) do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control', rows: 6 %>
      </div>
      <%= f.submit 'Post', class: 'btn btn-dark btn-block' %>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Books Channel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Books Channel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS 読み込み-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Bootstrap JS 読み込み-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>